name: compass_shared
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
