name: web_startup_analyzer
description: "Captures web startup timing data in a Flutter web app"
version: 0.1.0-wip

environment:
  sdk: '>=3.4.0-16.0.dev <4.0.0'
  flutter: ">=3.19.0-0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  assets:
    - lib/web_startup_analyzer.js
