name: compass_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  compass_shared:
    path: ../shared
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail_image_network: ^1.2.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/destinations.json
