name: ng_companion
description: A flutter app with a counter that can be manipulated from JS.
publish_to: 'none'
version: 1.0.0

environment:
<<<<<<< HEAD
  sdk: ^3.3.1
=======
  sdk: ^3.3.0
  flutter: ">=3.19.0"
>>>>>>> 4f568ebe645751233f97945af9322d6ea1cc7317

dependencies:
  flutter:
    sdk: flutter
  web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
