name: asset_transformation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-109.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  vector_graphics_compiler: ^1.1.11+1
  grayscale_transformer:
    path: ./grayscale_transformer

flutter:
  uses-material-design: true
  assets:
    - path: assets/colorful.jpg
      transformers:
        - package: grayscale_transformer
    - path: assets/svg.svg
      transformers:
        - package: vector_graphics_compiler
